version: '2'
services:
  db:
    image: postgres

    container_name: grules-db

    volumes:
      - /docker/postgres/data:/var/lib/postgresql/data

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: "grules"
      POSTGRES_PASSWORD: "grules"
      POSTGRES_DB: "grules"

